### ISSUE TITLE
the entity of the Shulker projectile has lost the ability to aim and change the vector

### ISSUE THREAD

**Issue by guardian3301** [FrozenBlock/FrozenLib#39] opened 2024-02-09 16:21 UTC
**The Shulker projectile cannot fire in other directions except -y**

**Steps To Reproduce**
1. _**just find shulker**_

**viedo**

https://github.com/FrozenBlock/FrozenLib/assets/143828404/9bb45ca6-6e74-4769-aed8-43b8506c0b3f

**Comment by AViewFromTheTop** [comment] 2024-02-09 16:26
Duplicate of #38 which is already fixed.
Just have to wait for the next release.

**Closed by AViewFromTheTop** 2024-02-09 16:26 UTC
Labels: bug

**Comment by guardian3301** [comment] 2024-02-09 16:42
> Duplicate of #38 which is already fixed. Just have to wait for the next release.

that's great, but how long is the wait?
